// process 是指:当前正在运行的nodejs进程.

// console.log(process)
// node .\src\day12\process.ts
// PS C:\Users\hinso\repos\node-backend-roadmap> node .\src\day12\process.ts
// process {
//   version: 'v24.20.0',
//   versions: {
//     node: '24.20.0',
//     acorn: '8.18.0',
//     ada: '4.0.0',
//     amaro: '1.1.11',
//     ares: '1.34.8',
//     brotli: '1.2.0',
//     cldr: '48.0',
//     icu: '78.3',
//     llhttp: '9.4.3',
//     merve: '1.2.2',
//     modules: '137',
//     napi: '10',
//     nbytes: '0.1.4',
//     ncrypto: '0.0.1',
//     nghttp2: '1.70.0',
//     nghttp3: '',
//     ngtcp2: '',
//     openssl: '3.5.7',
//     simdjson: '4.6.6',
//     simdutf: '6.4.0',
//     sqlite: '3.53.4',
//     tz: '2026c',
//     undici: '7.29.0',
//     unicode: '17.0',
//     uv: '1.52.1',
//     uvwasi: '0.0.23',
//     v8: '13.6.233.17-node.53',
//     zlib: '1.3.2.1-motley-42c2f19',
//     zstd: '1.5.7'
//   },
//   arch: 'x64',
//   platform: 'win32',
//   release: {
//     name: 'node',
//     lts: 'Krypton',
//     sourceUrl: 'https://nodejs.org/download/release/v24.20.0/node-v24.20.0.tar.gz',
//     headersUrl: 'https://nodejs.org/download/release/v24.20.0/node-v24.20.0-headers.tar.gz',
//     libUrl: 'https://nodejs.org/download/release/v24.20.0/win-x64/node.lib'
//   },
//   _rawDebug: [Function: _rawDebug],
//   moduleLoadList: [
//     'Internal Binding builtins',
//     'Internal Binding module_wrap',
//     'Internal Binding errors',
//     'NativeModule internal/assert',
//     'Internal Binding util',
//     'NativeModule internal/errors',
//     'Internal Binding config',
//     'Internal Binding timers',
//     'Internal Binding task_queue',
//     'Internal Binding async_wrap',
//     'Internal Binding symbols',
//     'NativeModule internal/async_hooks',
//     'Internal Binding constants',
//     'Internal Binding types',
//     'Internal Binding options',
//     'NativeModule internal/options',
//     'Internal Binding string_decoder',
//     'NativeModule internal/util',
//     'NativeModule internal/util/types',
//     'NativeModule internal/validators',
//     'NativeModule internal/linkedlist',
//     'NativeModule internal/priority_queue',
//     'Internal Binding icu',
//     'NativeModule internal/util/inspect',
//     'NativeModule internal/constants',
//     'Internal Binding trace_events',
//     'NativeModule internal/util/debuglog',
//     'Internal Binding async_context_frame',
//     'NativeModule internal/async_context_frame',
//     'NativeModule internal/timers',
//     'NativeModule internal/events/abort_listener',
//     'NativeModule events',
//     'Internal Binding buffer',
//     'NativeModule util/types',
//     'NativeModule internal/buffer',
//     'Internal Binding mksnapshot',
//     'NativeModule internal/v8/startup_snapshot',
//     'NativeModule buffer',
//     'NativeModule internal/webidl',
//     'Internal Binding messaging',
//     'NativeModule internal/worker/js_transferable',
//     'Internal Binding diagnostics_channel',
//     'NativeModule diagnostics_channel',
//     'Internal Binding process_methods',
//     'NativeModule internal/process/per_thread',
//     'Internal Binding credentials',
//     'NativeModule internal/fixed_queue',
//     'NativeModule internal/process/promises',
//     'NativeModule async_hooks',
//     'NativeModule internal/process/task_queues',
//     'NativeModule timers',
//     'NativeModule path',
//     'Internal Binding url_pattern',
//     'NativeModule internal/querystring',
//     'NativeModule internal/mime',
//     'NativeModule internal/data_url',
//     'NativeModule querystring',
//     'Internal Binding url',
//     'NativeModule internal/url',
//     'Internal Binding modules',
//     'NativeModule internal/modules/typescript',
//     'Internal Binding contextify',
//     'NativeModule internal/vm',
//     'NativeModule internal/process/execution',
//     'NativeModule internal/process/warning',
//     'Internal Binding fs',
//     'Internal Binding blob',
//     'NativeModule internal/encoding/single-byte',
//     'NativeModule internal/encoding/util',
//     'Internal Binding encoding_binding',
//     'NativeModule internal/encoding',
//     'NativeModule internal/blob',
//     'NativeModule internal/fs/utils',
//     'Internal Binding permission',
//     'NativeModule internal/process/permission',
//     'NativeModule fs',
//     'NativeModule internal/source_map/source_map_cache',
//     'NativeModule internal/modules/helpers',
//     'NativeModule internal/console/constructor',
//     'NativeModule internal/console/global',
//     'NativeModule internal/util/inspector',
//     'Internal Binding inspector',
//     'NativeModule internal/streams/utils',
//     'NativeModule util',
//     'Internal Binding performance',
//     'NativeModule internal/perf/utils',
//     'NativeModule internal/event_target',
//     'Internal Binding wasm_web_api',
//     'NativeModule internal/process/signal',
//     'NativeModule url',
//     'NativeModule internal/modules/customization_hooks',
//     'NativeModule internal/modules/package_json_reader',
//     'NativeModule internal/modules/package_map',
//     'NativeModule internal/modules/cjs/loader',
//     'NativeModule internal/modules/esm/assert',
//     'NativeModule internal/modules/esm/module_map',
//     'NativeModule internal/modules/esm/module_job',
//     'NativeModule internal/modules/esm/utils',
//     'NativeModule internal/modules/esm/get_format',
//     'NativeModule internal/modules/esm/load',
//     ... 47 more items
//   ],
//   binding: [Function: binding],
//   _linkedBinding: [Function: _linkedBinding],
//   _events: [Object: null prototype] {
//     newListener: [
//       [Function (anonymous)],
//       [Function: startListeningIfSignal],
//       Symbol(events.emitting): 0
//     ],
//     removeListener: [
//       [Function (anonymous)],
//       [Function: stopListeningIfSignal],
//       Symbol(events.emitting): 0
//     ],
//     warning: [Function: onWarning],
//     SIGWINCH: [
//       [Function: refreshStdoutOnSigWinch],
//       [Function: refreshStderrOnSigWinch],
//       Symbol(events.emitting): 0
//     ]
//   },
//   _eventsCount: 4,
//   _maxListeners: undefined,
//   domain: null,
//   _exiting: [Getter/Setter],
//   exitCode: [Getter/Setter],
//   config: {
//     variables: {
//       use_ccache_win: 0,
//       clang: 1,
//       llvm_version: '19.1.5',
//       nasm_version: '3.02',
//       node_enable_experimentals: false,
//       node_prefix: '\\usr\\local',
//       node_install_npm: true,
//       node_install_corepack: true,
//       control_flow_guard: false,
//       node_use_amaro: true,
//       debug_node: false,
//       debug_symbols: false,
//       error_on_warn: false,
//       suppress_all_error_on_warn: false,
//       use_prefix_to_find_headers: false,
//       host_arch: 'x64',
//       target_arch: 'x64',
//       node_byteorder: 'little',
//       want_separate_host_toolset: 0,
//       node_use_node_snapshot: true,
//       node_use_node_code_cache: true,
//       node_write_snapshot_as_array_literals: true,
//       node_enable_v8_vtunejit: false,
//       enable_pgo_generate: false,
//       enable_pgo_use: false,
//       enable_lto: false,
//       enable_thin_lto: false,
//       single_executable_application: true,
//       node_with_ltcg: true,
//       node_tag: '',
//       node_release_urlbase: 'https://nodejs.org/download/release/',
//       node_debug_lib: false,
//       debug_nghttp2: false,
//       node_no_browser_globals: false,
//       node_shared: false,
//       libdir: 'lib',
//       node_module_version: 137,
//       shlib_suffix: 'so.137',
//       asan: 0,
//       ubsan: 0,
//       coverage: false,
//       node_target_type: 'executable',
//       node_library_files: [Array],
//       node_cctest_sources: [Array],
//       napi_build_version: '10',
//       node_shared_zlib: false,
//       node_shared_http_parser: false,
//       node_shared_libuv: false,
//       node_shared_ada: false,
//       node_shared_simdjson: false,
//       node_shared_simdutf: false,
//       node_shared_brotli: false,
//       node_shared_cares: false,
//       node_shared_gtest: false,
//       node_shared_hdr_histogram: false,
//       node_shared_merve: false,
//       node_shared_nbytes: false,
//       node_shared_nghttp2: false,
//       node_shared_nghttp3: false,
//       node_shared_ngtcp2: false,
//       node_use_sqlite: true,
//       node_shared_sqlite: false,
//       node_shared_uvwasi: false,
//       node_shared_zstd: false,
//       v8_enable_webassembly: 1,
//       v8_enable_javascript_promise_hooks: 1,
//       v8_enable_lite_mode: 0,
//       v8_enable_gdbjit: 0,
//       v8_optimized_debug: 1,
//       dcheck_always_on: 0,
//       v8_enable_object_print: 1,
//       v8_random_seed: 0,
//       v8_promise_internal_field_count: 1,
//       v8_use_siphash: 1,
//       v8_enable_maglev: 1,
//       v8_enable_pointer_compression: 0,
//       v8_enable_sandbox: 0,
//       v8_enable_pointer_compression_shared_cage: 0,
//       v8_enable_external_code_space: 0,
//       v8_enable_31bit_smis_on_64bit_arch: 0,
//       v8_enable_extensible_ro_snapshot: 0,
//       v8_trace_maps: 0,
//       node_use_v8_platform: true,
//       node_use_bundled_v8: true,
//       force_dynamic_crt: 0,
//       node_enable_d8: false,
//       node_enable_v8windbg: false,
//       v8_enable_hugepage: 0,
//       v8_enable_short_builtin_calls: 1,
//       v8_enable_wasm_simd256_revec: 1,
//       node_use_openssl: true,
//       node_shared_openssl: false,
//       openssl_is_fips: false,
//       node_fipsinstall: false,
//       node_without_node_options: false,
//       openssl_version: 810549375,
//       openssl_is_boringssl: false,
//       node_use_quic: false,
//       icu_small: false,
//       v8_enable_i18n_support: 1,
//       icu_gyp_path: 'tools/icu/icu-generic.gyp',
//       icu_path: 'deps/icu-small',
//       icu_ver_major: '78',
//       icu_endianness: 'l',
//       icu_data_in: '..\\..\\deps\\icu-tmp\\icudt78l.dat',
//       v8_enable_inspector: 1,
//       node_builtin_shareable_builtins: [Array],
//       ossfuzz: false
//     },
//     target_defaults: {
//       include_dirs: [],
//       libraries: [],
//       defines: [Array],
//       cflags: [],
//       default_configuration: 'Release',
//       configurations: [Object]
//     }
//   },
//   dlopen: [Function: dlopen],
//   uptime: [Function: uptime],
//   _getActiveRequests: [Function: _getActiveRequests],
//   _getActiveHandles: [Function: _getActiveHandles],
//   getActiveResourcesInfo: [Function: getActiveResourcesInfo],
//   reallyExit: [Function: reallyExit],
//   _kill: [Function: _kill],
//   loadEnvFile: [Function: loadEnvFile],
//   cpuUsage: [Function: cpuUsage],
//   threadCpuUsage: [Function: threadCpuUsage],
//   resourceUsage: [Function: resourceUsage],
//   memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
//   constrainedMemory: [Function: constrainedMemory],
//   availableMemory: [Function: availableMemory],
//   kill: [Function: kill],
//   exit: [Function: exit],
//   execve: [Function: execve],
//   ref: [Function: ref],
//   unref: [Function: unref],
//   finalization: [Getter/Setter],
//   hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
//   openStdin: [Function (anonymous)],
//   allowedNodeEnvironmentFlags: [Getter/Setter],
//   features: {
//     inspector: true,
//     debug: false,
//     uv: true,
//     ipv6: true,
//     tls_alpn: true,
//     tls_sni: true,
//     tls_ocsp: true,
//     tls: true,
//     openssl_is_boringssl: false,
//     cached_builtins: [Getter],
//     require_module: [Getter],
//     quic: [Getter],
//     typescript: [Getter]
//   },
//   _fatalException: [Function (anonymous)],
//   setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback],
//   hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
//   emitWarning: [Function: emitWarning],
//   nextTick: [Function: nextTick],
//   _tickCallback: [Function: runNextTicks],
//   sourceMapsEnabled: [Getter],
//   setSourceMapsEnabled: [Function: setSourceMapsEnabled],
//   getBuiltinModule: [Function: getBuiltinModule],
//   _debugProcess: [Function: _debugProcess],
//   _debugEnd: [Function: _debugEnd],
//   _startProfilerIdleNotifier: [Function (anonymous)],
//   _stopProfilerIdleNotifier: [Function (anonymous)],
//   stdout: [Getter],
//   stdin: [Getter],
//   stderr: [Getter],
//   abort: [Function: abort],
//   umask: [Function: wrappedUmask],
//   chdir: [Function: wrappedChdir],
//   cwd: [Function: wrappedCwd],
//   env: {
//     ALLUSERSPROFILE: 'C:\\ProgramData',
//     APPDATA: 'C:\\Users\\hinso\\AppData\\Roaming',
//     CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_23592_KYDPXONJRMMEMIFI',
//     COMPUTERNAME: 'YZB',
//     ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
//     CommonProgramFiles: 'C:\\Program Files\\Common Files',
//     'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
//     CommonProgramW6432: 'C:\\Program Files\\Common Files',
//     DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
//     EFC_4596_1592913036: '1',
//     EFC_4596_2946480783: '1',
//     EFC_4596_344590478: '1',
//     EFC_4596_4126798990: '1',
//     FNM_ARCH: 'x64',
//     FNM_COREPACK_ENABLED: 'false',
//     FNM_DIR: 'C:\\Users\\hinso\\AppData\\Roaming\\fnm',
//     FNM_LOGLEVEL: 'info',
//     FNM_MULTISHELL_PATH: 'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158',
//     FNM_NODE_DIST_MIRROR: 'https://nodejs.org/dist',
//     FNM_RESOLVE_ENGINES: 'true',
//     FNM_VERSION_FILE_STRATEGY: 'local',
//     FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
//     FPS_BROWSER_USER_PROFILE_STRING: 'Default',
//     HOMEDRIVE: 'C:',
//     HOMEPATH: '\\Users\\hinso',
//     LOCALAPPDATA: 'C:\\Users\\hinso\\AppData\\Local',
//     LOGONSERVER: '\\\\YZB',
//     NUMBER_OF_PROCESSORS: '8',
//     OS: 'Windows_NT',
//     OneDrive: 'C:\\Users\\hinso\\OneDrive',
//     OneDriveConsumer: 'C:\\Users\\hinso\\OneDrive',
//     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
//     PROCESSOR_ARCHITECTURE: 'AMD64',
//     PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 142 Stepping 12, GenuineIntel',
//     PROCESSOR_LEVEL: '6',
//     PROCESSOR_REVISION: '8e0c',
//     PSModulePath: 'C:\\Users\\hinso\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
//     PUBLIC: 'C:\\Users\\Public',
//     Path: 'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158;c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand;c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Tencent\\寰俊web寮€鍙戣€呭伐鍏?C:\\Users\\hinso\\.local\\bin;C:\\Users\\hinso\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\hinso\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\hinso\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe;C:\\Users\\hinso\\AppData\\Local\\Programs\\DockerDesktop\\resources\\bin',
//     ProgramData: 'C:\\ProgramData',
//     ProgramFiles: 'C:\\Program Files',
//     'ProgramFiles(x86)': 'C:\\Program Files (x86)',
//     ProgramW6432: 'C:\\Program Files',
//     SESSIONNAME: 'Console',
//     SystemDrive: 'C:',
//     SystemRoot: 'C:\\WINDOWS',
//     TEMP: 'C:\\Users\\hinso\\AppData\\Local\\Temp',
//     TMP: 'C:\\Users\\hinso\\AppData\\Local\\Temp',
//     USERDOMAIN: 'YZB',
//     USERDOMAIN_ROAMINGPROFILE: 'YZB',
//     USERNAME: 'hinso',
//     USERPROFILE: 'C:\\Users\\hinso',
//     VSCODE_PYTHON_AUTOACTIVATE_GUARD: '1',
//     ZES_ENABLE_SYSMAN: '1',
//     windir: 'C:\\WINDOWS',
//     TERM_PROGRAM: 'vscode',
//     TERM_PROGRAM_VERSION: '1.136.1',
//     LANG: 'zh_CN.UTF-8',
//     COLORTERM: 'truecolor',
//     COPILOT_DEBUG_NONCE: '289048066c504a206c5150b0b11d1caf',
//     GIT_ASKPASS: 'c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\vscode.git\\askpass\\70789581cae28aa7\\askpass.sh',
//     VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\hinso\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
//     VSCODE_GIT_ASKPASS_EXTRA_ARGS: '',
//     VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\vscode.git\\askpass\\70789581cae28aa7\\askpass-main.js',
//     VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-8177be005b-sock',
//     VSCODE_INJECTION: '1'
//   },
//   title: 'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158\\node.exe',
//   argv: [
//     'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158\\node.exe',
//     'C:\\Users\\hinso\\repos\\node-backend-roadmap\\src\\day12\\process.ts'
//   ],
//   execArgv: [],
//   pid: 12460,
//   ppid: 6536,
//   execPath: 'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158\\node.exe',
//   debugPort: 9229,
//   argv0: 'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158\\node.exe',
//   _preload_modules: [],
//   report: [Getter],
//   Symbol(shapeMode): false,
//   Symbol(kCapture): false
// }

console.log(process.pid) // 12460

// 最重要的4个
// process.env
// process.cwd()
// process.argv
// process.exit()

// 2 process.argv
// argv => argument vector 参数列表
console.log(process.argv)
// node .\src\day12\process.ts
// PS C:\Users\hinso\repos\node-backend-roadmap> node .\src\day12\process.ts
// [
//   'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158\\node.exe',
//   'C:\\Users\\hinso\\repos\\node-backend-roadmap\\src\\day12\\process.ts'
// ]

console.log(process.argv)
console.log(process.argv.slice(2))
// node .\src\day12\process.ts 1 2 3
// [
//   'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158\\node.exe',
//   'C:\\Users\\hinso\\repos\\node-backend-roadmap\\src\\day12\\process.ts',
//   '1',
//   '2',
//   '3'
// ]
// [ '1', '2', '3' ]

// 3 cli是什么
// cli: command line interface 命令行界面

// 4 process.cwd()
// current working directory 当前工作目录
console.log(process.cwd())
// PS C:\Users\hinso\repos\node-backend-roadmap> node .\src\day12\process.ts 1 2 3
// C:\Users\hinso\repos\node-backend-roadmap
// 说白了就是在哪个目录下开始执行的nodejs进程.

// 5 process.env
// 读取环境变量.
// console.log(process.env)
// node .\src\day12\process.ts
// {
//   ALLUSERSPROFILE: 'C:\\ProgramData',
//   APPDATA: 'C:\\Users\\hinso\\AppData\\Roaming',
//   CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_23592_KYDPXONJRMMEMIFI',
//   COMPUTERNAME: 'YZB',
//   ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
//   CommonProgramFiles: 'C:\\Program Files\\Common Files',
//   'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
//   CommonProgramW6432: 'C:\\Program Files\\Common Files',
//   DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
//   EFC_4596_1592913036: '1',
//   EFC_4596_2946480783: '1',
//   EFC_4596_344590478: '1',
//   EFC_4596_4126798990: '1',
//   FNM_ARCH: 'x64',
//   FNM_COREPACK_ENABLED: 'false',
//   FNM_DIR: 'C:\\Users\\hinso\\AppData\\Roaming\\fnm',
//   FNM_LOGLEVEL: 'info',
//   FNM_MULTISHELL_PATH: 'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158',
//   FNM_NODE_DIST_MIRROR: 'https://nodejs.org/dist',
//   FNM_RESOLVE_ENGINES: 'true',
//   FNM_VERSION_FILE_STRATEGY: 'local',
//   FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
//   FPS_BROWSER_USER_PROFILE_STRING: 'Default',
//   HOMEDRIVE: 'C:',
//   HOMEPATH: '\\Users\\hinso',
//   LOCALAPPDATA: 'C:\\Users\\hinso\\AppData\\Local',
//   LOGONSERVER: '\\\\YZB',
//   NODE_ENV: 'hehe',
//   NUMBER_OF_PROCESSORS: '8',
//   OS: 'Windows_NT',
//   OneDrive: 'C:\\Users\\hinso\\OneDrive',
//   OneDriveConsumer: 'C:\\Users\\hinso\\OneDrive',
//   PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
//   PROCESSOR_ARCHITECTURE: 'AMD64',
//   PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 142 Stepping 12, GenuineIntel',
//   PROCESSOR_LEVEL: '6',
//   PROCESSOR_REVISION: '8e0c',
//   PSModulePath: 'C:\\Users\\hinso\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
//   PUBLIC: 'C:\\Users\\Public',
//   Path: 'C:\\Users\\hinso\\AppData\\Local\\fnm_multishells\\12352_1788700473158;c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand;c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Tencent\\寰俊web寮€鍙戣€呭伐鍏?C:\\Users\\hinso\\.local\\bin;C:\\Users\\hinso\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\hinso\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\hinso\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe;C:\\Users\\hinso\\AppData\\Local\\Programs\\DockerDesktop\\resources\\bin',
//   ProgramData: 'C:\\ProgramData',
//   ProgramFiles: 'C:\\Program Files',
//   'ProgramFiles(x86)': 'C:\\Program Files (x86)',
//   ProgramW6432: 'C:\\Program Files',
//   SESSIONNAME: 'Console',
//   SystemDrive: 'C:',
//   SystemRoot: 'C:\\WINDOWS',
//   TEMP: 'C:\\Users\\hinso\\AppData\\Local\\Temp',
//   TMP: 'C:\\Users\\hinso\\AppData\\Local\\Temp',
//   USERDOMAIN: 'YZB',
//   USERDOMAIN_ROAMINGPROFILE: 'YZB',
//   USERNAME: 'hinso',
//   USERPROFILE: 'C:\\Users\\hinso',
//   VSCODE_PYTHON_AUTOACTIVATE_GUARD: '1',
//   ZES_ENABLE_SYSMAN: '1',
//   windir: 'C:\\WINDOWS',
//   TERM_PROGRAM: 'vscode',
//   TERM_PROGRAM_VERSION: '1.136.1',
//   LANG: 'zh_CN.UTF-8',
//   COLORTERM: 'truecolor',
//   COPILOT_DEBUG_NONCE: '289048066c504a206c5150b0b11d1caf',
//   GIT_ASKPASS: 'c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\vscode.git\\askpass\\70789581cae28aa7\\askpass.sh',
//   VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\hinso\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
//   VSCODE_GIT_ASKPASS_EXTRA_ARGS: '',
//   VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\hinso\\AppData\\Roaming\\Code\\User\\globalStorage\\vscode.git\\askpass\\70789581cae28aa7\\askpass-main.js',
//   VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-8177be005b-sock',
//   VSCODE_INJECTION: '1'
// }

//  6 process.exit()
// process.exit(1)

// const filename = process.argv[2]

// if (!filename) {
//   console.error('请提供文件名字')
//   process.exit(1)
// }
